#!/usr/bin/env bash

function main ()
{
	local -r bin="/usr/bin/php-cgi"
	local -r nice="/bin/nice"
	local -r niceness="15"

	local bin_options
	local option
	local -a options
	local tmp="/var/tmp"

	# Parse options
	while [[ "${#}" -gt 0 ]]
	do
		case "${1}" in
			-d)
				options+=("${2}")
				shift 2
				;;
			--tmp=*)
				tmp="${1#*=}"
				shift 1
				;;
		esac
	done

	if [[ ${#options[@]} -gt 0 ]]
	then
		for option in "${options[@]}"
		do
			bin_options+=" -d ${option}"
		done
	fi

	# PHP child process management should always be disabled with mod_fcgid
	export PHP_FCGI_CHILDREN="0"
	export PHP_FCGI_MAX_REQUESTS="15000"
	export PHPRC="/etc"
	export REDIRECT_STATUS="200"
	export TMP="${tmp}"
	export TEMP="${tmp}"
	export TMPDIR="${tmp}"

	# FastCGI-enabled PHP executable
	exec ${nice} \
		-n ${niceness} \
		${bin} \
		${bin_options}
}

main "${@}"
